#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TomOne.Resource", IsApplication=true)]

namespace TomOne
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_camera = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_delete = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_locate = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_map = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_navizon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_new = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_new_picture = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_refresh = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_save = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int map = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int t_studio = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int t_studio_w = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001a
			public const int actionDelete = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int actionNew = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int actionRefresh = 2131099676;
			
			// aapt resource value: 0x7f060019
			public const int actionSave = 2131099673;
			
			// aapt resource value: 0x7f060008
			public const int addrEditText = 2131099656;
			
			// aapt resource value: 0x7f060017
			public const int addrTextView = 2131099671;
			
			// aapt resource value: 0x7f060006
			public const int descrEditText = 2131099654;
			
			// aapt resource value: 0x7f060018
			public const int distanceTextView = 2131099672;
			
			// aapt resource value: 0x7f06000e
			public const int latEditText = 2131099662;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060010
			public const int linearLayout2 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int locationImageButton = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int longEditText = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int mapImageButton = 2131099666;
			
			// aapt resource value: 0x7f060004
			public const int nameEditText = 2131099652;
			
			// aapt resource value: 0x7f060016
			public const int nameTextView = 2131099670;
			
			// aapt resource value: 0x7f060013
			public const int photoImageButton = 2131099667;
			
			// aapt resource value: 0x7f060002
			public const int poiImageView = 2131099650;
			
			// aapt resource value: 0x7f060014
			public const int poiListView = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int relativeLayout1 = 2131099669;
			
			// aapt resource value: 0x7f060000
			public const int scrollView1 = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int tableLayout1 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int tableRow1 = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int tableRow2 = 2131099661;
			
			// aapt resource value: 0x7f060003
			public const int textView1 = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int textView10 = 2131099660;
			
			// aapt resource value: 0x7f060005
			public const int textView2 = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int textView3 = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int textView9 = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int POIDetail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int POIList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int POIListItem = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int POIDetailMenu = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int POIListViewMenu = 2131034113;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
